package postgres_test

import (
	"context"
	"database/sql"
	"testing"
	"time"

	_ "github.com/jackc/pgx/v5/stdlib"
	"github.com/smartwalle/dbs"
	"github.com/smartwalle/dbs/dialect/postgres"
	"github.com/smartwalle/dotenv"
)

func open(t testing.TB) dbs.Database {
	t.Helper()

	var env, err = dotenv.Load()
	if err != nil {
		t.Fatal(err)
	}

	var dsn = env.Get("DSN")
	if dsn == "" {
		t.Skip("set DSN in .env to run PostgreSQL mapper integration examples")
	}

	rawDB, err := sql.Open("pgx", dsn)
	if err != nil {
		t.Fatal(err)
	}
	rawDB.SetMaxOpenConns(3)
	rawDB.SetMaxIdleConns(1)

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if err = rawDB.PingContext(ctx); err != nil {
		_ = rawDB.Close()
		t.Fatal(err)
	}

	db := dbs.New(rawDB)
	db.UseDialect(postgres.Dialect())
	t.Cleanup(func() {
		_ = db.Close()
	})
	prepare(t, db)
	return db
}

func prepare(t testing.TB, db dbs.Database) {
	t.Helper()

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	// 准备一个专用于 PostgreSQL mapper 示例的表。表名使用 dbs_example_ 前缀，
	// 用来降低误碰业务表的概率，但调用方仍应只在测试库中运行这些示例。
	_, err := db.ExecContext(ctx, `
CREATE TABLE IF NOT EXISTS dbs_example_mail (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email TEXT NOT NULL DEFAULT '',
	status TEXT NOT NULL DEFAULT '',
	created_at TIMESTAMPTZ NULL,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	extra JSONB NULL
)`)
	if err != nil {
		t.Fatal(err)
	}

	// 每个测试都会重新构造夹具数据。这里先清空表并重置 identity，
	// 所以下面的 INSERT 是覆盖式 seed，不会随着多次测试执行而累计重复数据。
	if _, err = db.ExecContext(ctx, `TRUNCATE TABLE dbs_example_mail RESTART IDENTITY`); err != nil {
		t.Fatal(err)
	}

	// 固定插入 4 条覆盖标量、结构体、map 和 slice 扫描场景的数据。
	// 时间统一使用同一个 now，避免测试日志里出现无意义的时间差异。
	now := time.Now().UTC().Truncate(time.Microsecond)
	_, err = db.ExecContext(ctx, `
INSERT INTO dbs_example_mail (id, email, status, created_at, updated_at, extra)
VALUES
	(1, 'one@example.com', 'active', $1, $1, '{"age":18,"city":"Hangzhou","name":"one"}'),
	(2, 'two@example.com', 'inactive', $1, $1, '{"age":20,"city":"Shanghai","name":"two"}'),
	(3, 'three@example.com', 'active', $1, $1, '{"age":22,"city":"Beijing","name":"three"}'),
	(4, 'four@example.com', 'inactive', $1, $1, '{"age":24,"city":"Shenzhen","name":"four"}')`, now)
	if err != nil {
		t.Fatal(err)
	}

	// 手动插入 id 后，同步 PostgreSQL identity 序列到当前最大 id。
	// 这样后续 Repository.Create 不指定 id 时会从下一位继续生成。
	if _, err = db.ExecContext(ctx, `
SELECT setval(pg_get_serial_sequence('dbs_example_mail', 'id'), (SELECT MAX(id) FROM dbs_example_mail))`); err != nil {
		t.Fatal(err)
	}
}
